### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by seehat** [hananils/kirby-choices#1]
Thank you for this plugin. I love it and think that I found a bug. 

I think here it needs an `isset()`:
https://github.com/hananils/kirby-choices-methods/blob/324248027e6dbb3fc1d37c6a8315726cf8a96c7b/index.php#L26

like this:

```
if (count($options) && isset($options[0]['value'])) {
```

**Comment by nilshoerrmann** [comment]
Thanks for your report. I‘ll try to release an update next week.

**Comment by nilshoerrmann** [comment]
This should be fixed in version 2.
